### ISSUE TITLE
A suggestion

### ISSUE THREAD

**Issue by Waldenth** [openwhu/OpenWHU#33]
- [x]  Yes, I have read FAQ.
- [x]  Yes, I have read Project page and Docs.
- [x]  And yes, I already searched for current issues and this did not help me.
I suggest the manager of this project or organization should take the initiative to look for repo(s) in Github that has been created by former students. In my memory, there are many students (even myself) has create repo to storage homework、coursepaper and experiment docs. I think all of them will be glad to help your organization to build this project.  :-)

**Comment by Crescentm** [comment]
I've actually started collecting homework from many seniors. However, due to the scattered distribution of data and the fact that I am the only one working on it, the work is not progressing very fast, but I will keep on doing it.

By the way, I have invited you to join our organization and hope you will agree.

Apologize for not noticing the your accounts before, and a thousand thanks for your suggestion!
